branches:
  only:
  - master
language: python
python:
  - 2.7
before_install:
  - openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in travis_ci_mlugs_website.enc -out travis_ci_mlugs_website -d
install:
  - pip install pelican Markdown ghp-import
script:
  - bash deploy.sh
notifications:
  email: false
